import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata = {
	metadataBase: new URL('https://synchroyst.pro'),
	title: {
		default: 'Synchroyst | AI Growth Infrastructure - Automation Systems - Revenue Scaling',
		template: '%s | Synchroyst',
	},
	description:
		'Synchroyst builds AI-powered growth systems for businesses seeking automation, scalable marketing, and operational efficiency.',
	keywords: [
		'AI Growth Infrastructure',
		'Business Growth',
		'Scalable Growth',
		'Marketing Solutions',
		'Enterprise Growth',
		'Sales Optimization',
		'Digital Architecture',
		'Synchroyst',
		'AI Automation',
		'Customer Support',
		'AI Marketing',
		'AI Sales',
		'AI Customer Support',
		'AI Growth Engine',
		'AI Business Growth',
		'AI Scalable Growth',
		'AI Marketing Solutions',
		'AI Enterprise Growth',
		'AI Sales Optimization',
		'AI Digital Architecture',
		'AI Synchroyst',
		'AI Growth Engine',
		'AI Business Growth',
		'AI Scalable Growth',
		'AI Marketing Solutions',
		'AI Enterprise Growth',
		'AI Sales Optimization',
		'AI Digital Architecture',
		'AI Synchroyst',
		'Automation Systems',
		'Revenue Scaling',
		'Scalable Growth',
		'Marketing Solutions',
		'Enterprise Growth',
		'Sales Optimization',
		'Digital Architecture',
		'Synchroyst',
		'AI Automation',
		'Customer Support',
		'AI Marketing',
		'AI Sales',
		'AI Customer Support',
		'AI Growth Engine',
		'AI Business Growth',
		'AI Scalable Growth',
		'AI Marketing Solutions',
		'AI Enterprise Growth',
		'AI Sales Optimization',
		'AI Digital Architecture',
		'AI Synchroyst',
		'AI Growth Engine',
		'AI Business Growth',
		'AI Scalable Growth',
		'AI Marketing Solutions',
		'AI Enterprise Growth',
		'AI Sales Optimization',
		'AI Digital Architecture',
		'AI Synchroyst',
		'Ameer Hamza',
		'Ameer Hamza AI',
		'Ameer Hamza Growth Engine',
		'Ameer Hamza Business Growth',
		'Ameer Hamza Scalable Growth',
		'Ameer Hamza Marketing Solutions',
		'Ameer Hamza Enterprise Growth',
		'Ameer Hamza Sales Optimization',
		'Ameer Hamza Digital Architecture',
		'Ameer Hamza Synchroyst',
		'Ameer Hamza AI Automation',
		'Ameer Hamza Customer Support',
		'Ameer Hamza AI Marketing',
		'Ameer Hamza AI Sales',
		'Ameer Hamza AI Customer Support',
		'Ameer Hamza AI Growth Engine',
		'Ameer Hamza AI Business Growth',
		'Ameer Hamza AI Scalable Growth',
		'Ameer Hamza AI Marketing Solutions',
		'Ameer Hamza AI Enterprise Growth',
		'Ameer Hamza AI Sales Optimization',
		'Ameer Hamza AI Digital Architecture',
		'Ameer Hamza AI Synchroyst',
		'Ameer Hamza AI Growth Engine',
		'Ameer Hamza AI Business Growth',
		'Ameer Hamza AI Scalable Growth',
		'Ameer Hamza AI Marketing Solutions',
		'Ameer Hamza AI Enterprise Growth',
		'Ameer Hamza AI Sales Optimization',
		'Ameer Hamza AI Digital Architecture',
		'Ameer Hamza AI Synchroyst',
		'Qazi Abdul Ghani',
		'Qazi Abdul Ghani AI',
		'Qazi Abdul Ghani Growth Engine',
		'Qazi Abdul Ghani Business Growth',
		'Qazi Abdul Ghani Scalable Growth',
		'Qazi Abdul Ghani Marketing Solutions',
		'Qazi Abdul Ghani Enterprise Growth',
		'Qazi Abdul Ghani Sales Optimization',
		'Qazi Abdul Ghani Digital Architecture',
		'Qazi Abdul Ghani Synchroyst',
		'Qazi Abdul Ghani AI Automation',
		'Qazi Abdul Ghani Customer Support',
		'Qazi Abdul Ghani AI Marketing',
		'Qazi Abdul Ghani AI Sales',
		'Qazi Abdul Ghani AI Customer Support',
		'Qazi Abdul Ghani AI Growth Engine',
		'Qazi Abdul Ghani AI Business Growth',
		'Qazi Abdul Ghani AI Scalable Growth',
		'Qazi Abdul Ghani AI Marketing Solutions',
		'Qazi Abdul Ghani AI Enterprise Growth',
		'Qazi Abdul Ghani AI Sales Optimization',
		'Qazi Abdul Ghani AI Digital Architecture',
		'Qazi Abdul Ghani AI Synchroyst',
		'Qazi Abdul Ghani AI Growth Engine',
		'Qazi Abdul Ghani AI Business Growth',
		'Qazi Abdul Ghani AI Scalable Growth',
		'Qazi Abdul Ghani AI Marketing Solutions',
		'Qazi Abdul Ghani AI Enterprise Growth',
		'Qazi Abdul Ghani AI Sales Optimization',
		'Qazi Abdul Ghani AI Digital Architecture',
		'Qazi Abdul Ghani AI Synchroyst',
		'Automation Systems',
		'Revenue Scaling',
		'Scalable Growth',
		'Marketing Solutions',
		'Enterprise Growth',
		'Sales Optimization',
		'Digital Architecture',
		'Synchroyst',
		'AI Automation',
		'Customer Support',
		'AI Marketing',
		'AI Sales',
		'AI Customer Support',
		'AI Growth Engine',
		'AI Business Growth',
		'AI Scalable Growth',
		'AI Marketing Solutions',
		'AI Enterprise Growth',
		'AI Sales Optimization',
		'AI Digital Architecture',
		'AI Synchroyst',
		'AI Growth Engine',
		'AI Business Growth',
		'AI Scalable Growth',
		'AI Marketing Solutions',
		'AI Enterprise Growth',
		'AI Sales Optimization',
		'AI Digital Architecture',
		'AI Synchroyst',
		'Ameer Hamza',
		'Ameer Hamza AI',
		'Ameer Hamza Growth Engine',
		'Ameer Hamza Business Growth',
		'Ameer Hamza Scalable Growth',
		'Ameer Hamza Marketing Solutions',
		'Ameer Hamza Enterprise Growth',
		'Ameer Hamza Sales Optimization',
		'Ameer Hamza Digital Architecture',
		'Ameer Hamza Synchroyst',
		'Ameer Hamza AI Automation',
		'Ameer Hamza Customer Support',
		'Ameer Hamza AI Marketing',
		'Ameer Hamza AI Sales',
		'Ameer Hamza AI Customer Support',
		'Ameer Hamza AI Growth Engine',
		'Ameer Hamza AI Business Growth',
		'Ameer Hamza AI Scalable Growth',
		'Ameer Hamza AI Marketing Solutions',
		'Ameer Hamza AI Enterprise Growth',
		'Ameer Hamza AI Sales Optimization',
		'Ameer Hamza AI Digital Architecture',
		'Ameer Hamza AI Synchroyst',
		'Ameer Hamza AI Growth Engine',
		'Ameer Hamza AI Business Growth',
		'Ameer Hamza AI Scalable Growth',
		'Ameer Hamza AI Marketing Solutions',
		'Ameer Hamza AI Enterprise Growth',
		'Ameer Hamza AI Sales Optimization',
		'Ameer Hamza AI Digital Architecture',
		'Ameer Hamza AI Synchroyst',
	],
	authors: [{ name: 'Synchroyst' }],
	creator: 'Synchroyst',
	publisher: 'Synchroyst',
	formatDetection: {
		email: false,
		address: false,
		telephone: false,
	},
	openGraph: {
		title: 'Synchroyst | Enterprise-Grade Growth Engine',
		description:
			'Synchroyst provides enterprise-grade growth engines for growing businesses. Unlock scalable, sustainable growth today.',
		url: 'https://synchroyst.pro',
		siteName: 'Synchroyst',
		images: [
			{
				url: '/opengraph-image.jpg', // Next.js automatically looks for this file, but being explicit is good.
				width: 1200,
				height: 630,
				alt: 'Synchroyst - Enterprise-Grade Growth Engine',
			},
		],
		locale: 'en_US',
		type: 'website',
	},
	twitter: {
		card: 'summary_large_image',
		title: 'Synchroyst | Enterprise-Grade Growth Engine',
		images: ['/twitter-image.jpg'],
		description:
			'Synchroyst provides enterprise-grade growth engines for growing businesses. Unlock scalable, sustainable growth today.',
		creator: '@synchroyst', // Replace with actual handle if applicable
	},
	robots: {
		index: true,
		follow: true,
		googleBot: {
			index: true,
			follow: true,
			'max-video-preview': -1,
			'max-image-preview': 'large',
			'max-snippet': -1,
		},
	},
	icons: {
		icon: '/favicon.ico',
		shortcut: '/favicon-16x16.png',
		apple: '/apple-touch-icon.png',
	},
	manifest: '/site.webmanifest',
};

export default function RootLayout({ children }) {
	return (
		<html
			lang='en'
			className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
			suppressHydrationWarning>
			<body
				className='min-h-full flex flex-col'
				suppressHydrationWarning>
				{children}
			</body>
		</html>
	);
}
